import {
  Abhinandanraj,
  ashutoshsingh,
  Abhinavchandra,
  AdarshMishra,
  Adityasrivastav,
  Ajitpandey,
  Akashsaurav,
  Anishkumar,
  Archikumari,
  Arpitadwivedi,
  Arunsingh,
  Aryanranjan,
  Ashishyadav,
  Ayushshaw,
  Deepaksingh,
  Gauharmaqubool,
  Amansinha,
  Amitbaghel,
  Anjalikumari,
  Harshvardhan,
  Harshvardhandansena,
  Kirtanpatidar,
  Kushagra,
  Mahtabalam,
  Mayank,
  Mitalidwivedi,
  Monukumar,
  Munquabanwer,
  Muskan,
  Nishantkumar,
  Piyushprasad,
  Priteshutkarsh,
  PriyaKanaujia,
  Priyanshu,
  Rahulkumar,
  Rishavanand,
  Ritikaranjan,
  Sagarkumar,
  Salonikushwaha,
  Sameergupta,
  Shailendrayadav,
  Shanvidixit,
  Subodhkumar,
  Suyashkrishna,
  Tusharpradhan,
  Vanikumari,
  Manshi,
  Viverkumar,
  img
} from "../../assets/teamsprofile/index.js";
// akash-event lead, anish , priyanshu-event colead, ashutosh singh chief cordinator, arun singh-community engagemnet lead, deepak technical lead, munquab-outreach lead, ayush, abhinandan-web lead,Aman-archi-design lead, aman sinha-pr lead,suyashkrsihna-discpline lead, prakahrkri-content lead, bind-mentorship lead, mayank-Pr lead, harshvardhan-recrational lead, shailendra yadav treasurer, mahtabalam-media lead, ajit-technical, pritesh
const Leads = [
  {
    name: "Akash Saurav",
    role: "Event Lead",
    about: "",
    email: "ayushs.ug21.cs@nitp.ac.in",
    image: Akashsaurav,
    github: "https://github.com/akashslm10",
    twitter: "",
    instagram: "",
    linkedin:
      "https://www.linkedin.com/in/akash-saurav-89b4b2245?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    discord: "",
  },
  {
    name: "Priyanshu Raj",
    role: "Event Co-Lead",
    about: "",
    email: "priyanshur.ce@nitp.ac.in",
    image: Priyanshu,
    github: "https://github.com/Priyanshu8797",
    twitter: "",
    instagram: "",
    linkedin:
      "https://www.linkedin.com/in/priyanshu-raj-9bb1311b3?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    discord: "",
  },
  {
    name: "Anish Kumar",
    role: "Event Co-Lead",
    about: "",
    email: "anishk.me@nitp.ac.in",
    image: Anishkumar,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "",
    discord: "",
  },

  {
    name: "Ashutosh Singh",
    role: "Chief Cordinator",
    about: "",
    email: "ashutoshs.ug21.cs@nitp.ac.in",
    image: ashutoshsingh,
    github: "https://github.com/Ashutosh-1302",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/ashutosh-singh-328053229?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    discord: "",
  },
  {
    name: "Arun Singh",
    role: "Community Engagement Lead",
    about: "",
    email: "aruns.ug21.cs@nitp.ac.in",
    image: Arunsingh,
    github: "https://github.com/arunsingh2004",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/arun-singh-1a0b25225",
    discord: "",
  },

  {
    name: "Deepak Kumar",
    role: "Technical Lead",
    about: "",
    email: "ayushs.ug21.cs@nitp.ac.in",
    image: Deepaksingh,
    github: "https://github.com/deepaksinghcsebtech2025",
    twitter: "",
    instagram: "",
    linkedin:
      "https://www.linkedin.com/in/deepak-kumar-287917207?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    discord: "",
  },
  {
    name: "Mayank",
    role: "Lead",
    about: "Passionate about coding and creating meaningful software.",
    email: "http://mayankk.ug21.ee",
    image: Mayank,
    github: "https://github.com/mayankjha2021",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/mayank-jha-247080224",
    discord: "",
  },
  {
    name: "Munquab Anwer",
    role: "Outreach Lead",
    about: "",
    email: "munquaba.ug21.cs@nitp.ac.in",
    image: Munquabanwer,
    github: "https://github.com/munquaba",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/munquab-anwer-481a93236",
    discord: "",
  },
  {
    name: "Suyash Krishna",
    role: "Lead",
    about: "Passionate about coding and creating meaningful software.",
    email: "suyashk.ug21.ce@nitp.ac.in",
    image: Suyashkrishna,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/skrish11",
    discord: "",
  },
  {
    name: "Ayush Kumar shaw",
    role: "Website Lead",
    about: "",
    email: "ayushs.ug21.cs@nitp.ac.in",
    image: Ayushshaw,
    github: "https://github.com/ayushshaw016",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/ayush-kumar-shaw-ba671928b",
    discord: "",
  },
  {
    name: "Abhinandan Raj",
    role: "Website Lead",
    about: "",
    email: "abhinandanr.ug21.cs@nitp.ac.in",
    image: Abhinandanraj,
    github: "https://github.com/abhi2003-drigger",
    twitter: "",
    instagram: "",
    linkedin:
      "https://www.linkedin.com/in/abhinandan-raj-he-him-95ba31222?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    discord: "",
  },
  {
    name: "Aman Gupta",
    role: "Design-Lead",
    about: "",
    email: "",
    image: img,
    github: "",
    twitter: "",
    instagram: "",
    linkedin:
      "",
    discord: "",
  },
  {
    name: "Bind Ashutosh",
    role: "Lead",
    about: "Passionate about coding and creating meaningful software.",
    email: "bindp.ug21.cs@nitp.ac.in",
    image: img,
    github: "https://github.com/Ashutoshbind15",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/ashutosh-bind-56806b22b/",
    discord: "",
  },
  {
    name: "Rishikesh Vaishnavi",
    role: "Lead",
    about: "Passionate about coding and creating meaningful software.",
    email: "",
    image: img,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "",
    discord: "",
  },
  {
    name: "Aman Sinha",
    role: "PR Lead",
    about: "Passionate about coding and creating meaningful software.",
    email: "amans.ug21.me@nitp.ac.in",
    image: Amansinha,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/aman-sinha-994b16227",
    discord: "",
  },
  
  {
    name: "Mitali Dwivedi",
    role: "PR Lead",
    about: "Passionate about coding and creating meaningful software.",
    email: "mitalidwivedi168@gmail.com",
    image: Mitalidwivedi,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/mitali-dwivedi-9ab40222b",
    discord: "",
  },
  
  {
    name: "Prakhar Krishna",
    role: "Lead",
    about: "Passionate about coding and creating meaningful software.",
    email: "prakhark.ug21.ce@nitp.ac.in",
    image: img,
    github:
      "https://drive.google.com/open?id=1BrOtKJkIMkrqpSAfdhWToxOfzmymVFaK",
    twitter: "",
    instagram: "",
    linkedin:
      "https://www.linkedin.com/in/prakhar-krishna-73803b250?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    discord: "",
  },
  {
    name: "Ajit Kuamr Pandey",
    role: "Lead",
    about: "Passionate about coding and creating meaningful software.",
    email: "ajitp.ec21.ce@nitp.ac.in",
    image: Ajitpandey,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/ajit-pandey-a03742174",
    discord: "",
  },
  {
    name: "Shubodh",
    role: "Lead",
    about: "Passionate about coding and creating meaningful software.",
    email: "a",
    image: img,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "",
    discord: "",
  },
  {
    name: "Harsh Vardhan",
    role: "Lead",
    about: "Passionate about coding and creating meaningful software.",
    email: "harshv.ug21.cs@nitp.ac.in",
    image: Harshvardhan,
    github: "https://github.com/kingsman00000",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/harsh-vardhan-4354b1237/",
    discord: "",
  },
  {
    name: "Aman Anand",
    role: "Lead",
    about: "Passionate about coding and creating meaningful software.",
    email: "",
    image: img,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "",
    discord: "",
  },
  {
    name: "Aditya Jaiswal",
    role: "Lead",
    about: "Passionate about coding and creating meaningful software.",
    email: "",
    image: img,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "",
    discord: "",
  },
  {
    name: "Sonali Raj",
    role: "Lead",
    about: "Passionate about coding and creating meaningful software.",
    email: "",
    image: img,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "",
    discord: "",
  },
  {
    name: "Shailendra Yadav",
    role: "Lead",
    about: "Passionate about coding and creating meaningful software.",
    email: "shailendray.ug21.ce@nitp.ac.in",
    image: Shailendrayadav,
    github: "",
    twitter: "",
    instagram: "",
    linkedin:
      "https://www.linkedin.com/in/shailendra-yadav-24960b222?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    discord: "",
  },
  {
    name: "Mahtab Alam",
    role: "Lead",
    about: "Passionate about coding and creating meaningful software.",
    email: "hshv.ug21.cs@nitp.ac.in",
    image: img,
    github: "hps://github.com/kingsman00000",
    twitter: "",
    instagram: "",
    linkedin: "htt://www.linkedin.com/in/harsh-vardhan-4354b1237/",
    discord: "",
  },
  {
    name: "Pritesh Utkarsh",
    role: "Lead",
    about: "Passionate about coding and creating meaningful software.",
    email: "priteshu.ec@nitp.ac.in",
    image: Priteshutkarsh,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/pritesh-utkarsh-6679a627b/",
    discord: "",
  },
  
];

const members = [{
    name: "Vani Kumari",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "vanik.ug22.ec@nitp.ac.in",
    image: Vanikumari,
    github: "https://github.com/Vani-Kumari",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/vani-singh-45645b245",
    discord: "",
  },

  {
    name: "Shanvi Dixit",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "shanvid.ug23.ch@nitp.ac.in",
    image: Shanvidixit,
    github: "",
    twitter: "",
    instagram: "",
    linkedin:
      "https://www.linkedin.com/in/shanvi-dixit-42ba75283?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    discord: "",
  },
  
  {
    name: "Rahul Kumar",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "rahulk.dd22.ec@nitp.ac.in",
    image: Rahulkumar,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "https://in.linkedin.com/in/rahul-kumar-690370202p",
    discord: "",
  },
  {
    name: "Manshi Shrivastava",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: " ",
    image: Manshi,
    github: "",
    twitter: "",
    instagram: "",
    linkedin:
      "https://www.linkedin.com/in/manshi-shrivastava-77299825b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    discord: "",
  },
  {
    name: "Muskan",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "raghvendras.ug22.me@nitp.ac.in",
    image: img,
    github: "",
    twitter: "",
    instagram: "",
    linkedin:
      "https://www.linkedin.com/in/muskan-sharma-99125b256?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    discord: "",
  },
  {
    name: "Arpita Diwedi",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "arpitad.ug22.cs@nitp.ac.in",
    image: Arpitadwivedi,
    github: "",
    twitter: "",
    instagram: "",
    linkedin:
      "https://www.linkedin.com/in/arpita-dwivedi-6bb002271?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    discord: "",
  },
  ,
  {
    name: "Aditya Srivastav",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "adityas2.ug22.ec@nitp.ac.in",
    image: Adityasrivastav,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/adityasri10938/",
    discord: "",
  },
  {
    name: "Amit Baghel",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "amitb.ug22.ec@nitp.ac.in",
    image: Amitbaghel,
    github: "",
    twitter: "",
    instagram: "",
    linkedin:
      "https://www.linkedin.com/in/amit-baghel-40810b273?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    discord: "",
  },
  {
    name: "Archi Kumari",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "archik.ug22.ce@nitp.ac.in",
    image: Archikumari,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/archi-kumari-527866257",
    discord: "",
  },
  {
    name: "Rishav Anand",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "rishava.ug22.ce@nitp.ac.in",
    image: Rishavanand,
    github: "",
    twitter: "",
    instagram: "",
    linkedin:
      "https://www.linkedin.com/in/rishav-anand-24718b281?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    discord: "",
  },
  {
    name: "Anjali Kumari",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "anjalikan.ug22.cs@nitp.ac.in",
    image: Anjalikumari,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/anjali-kumari-12aa07257",
    discord: "",
  },
  {
    name: "kushagra",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "kushagra.ug22.cs@nitp.ac.in",
    image: Kushagra,
    github: "",
    twitter: "",
    instagram: "",
    linkedin:
      "https://www.linkedin.com/in/kushagra-singh-888996258?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    discord: "",
  },
  {
    name: "Sameer Gupta",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "sameerg.ug22.ec@nitp.ac.in",
    image: Sameergupta,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/sameer-gupta-18a366259",
    discord: "",
  },
  ,
  // profile photo needed
  {
    name: "Anjali Rani",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "anjalir.ug22.ec@nitp.ac.in",
    image: img,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/anjali-rani-03975928b/",
    discord: "",
  },
  
  {
    name: "Subodh Kumar",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "subodhk.ug21.ec@nitp.ac.in",
    image: Subodhkumar,
    github: "",
    twitter: "",
    instagram: "",
    linkedin:
      "https://www.linkedin.com/in/subodh-kumar-1582ba224?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    discord: "",
  },
  {
    name: "Aryan Ranjan",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "aryanranjan@ieee.org",
    image: Aryanranjan,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/aryanranjan2005",
    discord: "",
  },

  {
    name: "Sagar Kumar",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "sagark.ug21.cs@nitp.ac.in",
    image: Sagarkumar,
    github: "http://github.com/sagarkumar2001",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/sagar-kumar-239a31237",
    discord: "",
  },
  

  {
    name: "Aman Anand",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "amana.ug21.ec@nitp.ac.in",
    image: img,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/aman-anand-a2422b256",
    discord: "",
  },
  {
    name: "Vivek Kumar Jha",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "vivekj.ug22.ce@nitp.ac.in",
    image: Viverkumar,
    github: "",
    twitter: "",
    instagram: "",
    linkedin:
      "https://www.linkedin.com/in/vivek-jha-827a5a298?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    discord: "",
  },
  {
    name: "Tushar Pradhan",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "tusharp.dd22.ec@nitp.ac.in",
    image: Tusharpradhan,
    github: "",
    twitter: "",
    instagram: "",
    linkedin:
      "https://www.linkedin.com/in/tushar-pradhan-373916257?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    discord: "",
  },
  {
    name: "Piyush Kumar Prasad",
    role: "",
    about: "Passionate about coding and creating meaningful software.",
    email: "piyushppd.ug22.cs@nitp.ac.in",
    image: Piyushprasad,
    github: "",
    twitter: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/piyushkumarprasad/",
    discord: "",
  }
  // Add more team members as needed
];

export { Leads, members };
